version: '3.1'

services:
  mirror-alpine:
    build:
      context: ./dockerfile
    image: alpine-mirror-repo:v1
    ports:
      - 80:80
    volumes:
      - ./data:/html/
    restart: always
    environment:
      - VIRTUAL_HOST
volumes:
  data: